/**
 * Robots.txt Generator
 * ====================
 * Generates robots.txt for search engine crawlers
 */

const fs = require('fs').promises;
const path = require('path');

/**
 * Ensure directory exists (async)
 * @param {string} dirPath - Directory path
 */
async function ensureDir(dirPath) {
  try {
    await fs.mkdir(dirPath, { recursive: true });
  } catch (error) {
    if (error.code !== 'EEXIST') {
      throw error;
    }
  }
}

/**
 * Generate robots.txt (async for reliable file operations)
 * @param {object} config - Site configuration
 * @param {string} rootDir - Root directory path
 * @returns {Promise<void>}
 */
async function generateRobots(config, rootDir) {
  const baseUrl = config.project.base_url.replace(/\/$/, '');
  const allowAll = config.build.robots.allow_all !== false;

  let robots = `# Robots.txt for ${config.project.name}
# Generated by Chiron Documentation Builder

User-agent: *
`;

  if (allowAll) {
    robots += `Allow: /
`;
  } else {
    robots += `Disallow: /
`;
  }

  // Add sitemap reference if enabled
  if (config.build.sitemap?.enabled) {
    robots += `
Sitemap: ${baseUrl}/sitemap.xml
`;
  }

  const outputPath = path.join(rootDir, config.build.output_dir, 'robots.txt');
  
  // Ensure directory exists
  await ensureDir(path.dirname(outputPath));
  
  // Write file asynchronously with explicit flush
  const fileHandle = await fs.open(outputPath, 'w');
  try {
    await fileHandle.writeFile(robots, 'utf8');
    // Explicitly sync to disk (critical for Windows)
    await fileHandle.sync();
  } finally {
    await fileHandle.close();
  }
}

module.exports = { generateRobots };
