/**
 * Robots.txt Generator
 * ====================
 * Generates robots.txt for search engine crawlers
 */

const fs = require('fs');
const path = require('path');

/**
 * Generate robots.txt
 * @param {object} config - Site configuration
 * @param {string} rootDir - Root directory path
 */
function generateRobots(config, rootDir) {
  const baseUrl = config.project.base_url.replace(/\/$/, '');
  const allowAll = config.build.robots.allow_all !== false;

  let robots = `# Robots.txt for ${config.project.name}
# Generated by Chiron Documentation Builder

User-agent: *
`;

  if (allowAll) {
    robots += `Allow: /
`;
  } else {
    robots += `Disallow: /
`;
  }

  // Add sitemap reference if enabled
  if (config.build.sitemap?.enabled) {
    robots += `
Sitemap: ${baseUrl}/sitemap.xml
`;
  }

  const outputPath = path.join(rootDir, config.build.output_dir, 'robots.txt');
  fs.writeFileSync(outputPath, robots, 'utf8');
}

module.exports = { generateRobots };
